#!/usr/bin/env cwl-runner

$namespaces:
  dct: http://purl.org/dc/terms/
  foaf: http://xmlns.com/foaf/0.1/
  s: http://schema.org/

$schemas:
- http://schema.org/docs/schema_org_rdfa.html
- http://dublincore.org/2012/06/14/dcterms.rdf
- http://xmlns.com/foaf/spec/20140114.rdf


class: CommandLineTool

id: "cgp-irap"

label: "Dockerised iRAP for RNAseq data analysis"

cwlVersion: v1.0

doc: |
    ![build_status](https://quay.io/repository/wtsicgp/dockstore-cgp-irap/status)
    A Docker container of iRAP. See the [dockstore-cgp-irap](https://github.com/cancerit/dockstore-cgp-irap) website for more information.

dct:creator:
  "@id": "yaobo.xu@sanger.ac.uk"
  foaf:name: Yaobo Xu
  foaf:mbox: "yx2@sanger.ac.uk"

requirements:
  - class: DockerRequirement
    dockerPull: "quay.io/wtsicgp/dockstore-cgp-irap:0.1.9"

hints:
  - class: ResourceRequirement
    coresMin: 1 # works but long, 8 recommended
    ramMin: 4000
    outdirMin: 80000

inputs:
  reference:
    type: File
    doc: "reference genome file in gzipped fasta format"
    inputBinding:
      prefix: -R
      position: 1
      separate: true
      shellQuote: true

  gtf:
    type: File
    doc: "a tar ball of GTF references generated by iRAP, or a single GTF file path"
    inputBinding:
      prefix: -g
      position: 2
      separate: true

  species:
    type: string
    doc: "species name"
    inputBinding:
      prefix: -s
      position: 3
      separate: true

  raw_read_file:
    type:
      type: array
      items: File
      inputBinding:
        prefix: -r
        separate: true
        shellQuote: true
    doc: "raw read files [bam|fastq]"
    inputBinding:
      position: 4

  exp_name:
    type: string?
    default: 'irap_analysis'
    doc: "analysis experiment name, iRAP use it to name the output folder as well"
    inputBinding:
      prefix: -o
      position: 5
      separate: true

  config:
    type: File?
    doc: "the configuration file for a analysis."
    inputBinding:
      prefix: -c
      position: 6
      separate: true
      shellQuote: true

  irap_conf_string:
    type:
      - "null"
      - type: array
        items: string
        inputBinding:
          prefix: -i
          separate: true
          shellQuote: true
    doc: "additional irap config strings"
    inputBinding:
      position: 7

  conta_genomes:
    type:
      - "null"
      - type: array
        items: File
        inputBinding:
          prefix: -m
          separate: true
          shellQuote: true
    doc: "contamination genomes in gzipped fasta format"
    inputBinding:
      position: 8

outputs:
  result_data:
    type: File
    outputBinding:
      glob: $(inputs.exp_name).tar.gz

  result_md5:
    type: File
    outputBinding:
      glob: $(inputs.exp_name).tar.gz.md5

  result_log:
    type: File
    outputBinding:
      glob: $(inputs.exp_name).log

baseCommand: ["irap_wrapper.sh"]

s:codeRepository: https://github.com/cancerit/dockstore-cgp-irap 
s:license: https://spdx.org/licenses/AGPL-3.0-only
s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0002-7638-2899 
    s:email: mailto:cgphelp@sanger.ac.uk
    s:name: Shriram Bhosle
